name: PvpPoints
version: '${project.version}'
main: me.indian.pl.Main
api-version: 1.19
authors: [ IndianPL ]
softdepend: [PlaceholderAPI]
commands:
  pvpr:
    description: reload command
  points:
    description: check points
    aliases:
      - punkty
  pvp:
    description: leade board



